# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-12 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='score.Score')),
            ],
        ),
    ]
