# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-12 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='id',
        ),
        migrations.AlterField(
            model_name='rank',
            name='score',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='score.Score'),
        ),
    ]
